const natural = require('natural');
const classifier = new natural.BayesClassifier();

// Ampliación del conjunto de datos
const dataSet = [
    { question: "¿Cómo estás?", intent: "saludo" },
    { question: "Hola, ¿cómo puedo ayudarte?", intent: "saludo" },
    { question: "Hola", intent: "saludo" },
    { question: "ola", intent: "saludo" },
    { question: "como estas", intent: "saludo" },
    { question: "que tal?", intent: "saludo" },
    { question: "que tal", intent: "saludo" },
    { question: "dónde están las prácticas profesionales disponibles", intent: "pasantias" },
    { question: "practicas profesionales en el campus?", intent: "pasantias" },
    { question: "dónde están las pasantías disponibles", intent: "pasantias" },
    { question: "practicas profesionales en el campus", intent: "pasantias" },
    { question: "¿cuándo es el período de inscripción para cursos en el campus?", intent: "fechaInscripcion" },
    { question: "cuándo es el período de inscripción para cursos en el campus?", intent: "fechaInscripcion" },
    { question: "cuándo es el período de inscripción para cursos en el campus", intent: "fechaInscripcion" },
    { question: "practicas profesionales en el campus?", intent: "pasantias" },
    { question: "¿practicas profesionales en el campus?", intent: "pasantias" },
    { question: "practicas profesionales en campus", intent: "pasantias" },
    { question: "dónde buscar pasantías relevantes para mi carrera", intent: "pasantias" },
    { question: "cuando es la fecha de inscripcion?", intent: "fechaInscripcion" },
    { question: "cuando es la fecha inscripcion?", intent: "fechaInscripcion" },
    { question: "cuando inscripcion cursos?", intent: "fechaInscripcion" },
    { question: "donde puedo encontrar pasantias?", intent: "pasantias" },
    { question: "donde encontrar pasantias?", intent: "pasantias" },
    { question: "donde estan las pasantias?", intent: "pasantias" },
    { question: "donde encontrar practicas profesionales?", intent: "pasantias" },
    { question: "donde estan las practicas profesionales?", intent: "pasantias" },
    { question: "practicas profesionales disponibles?", intent: "pasantias" },
    { question: "que clubes hay en el campus?", intent: "extracurriculares" },
    { question: "que clubes existen en el campus?", intent: "extracurriculares" },
    { question: "que actividades extracurriculares hay en el campus?", intent: "extracurriculares" },
    { question: "que clubes o actividades extracurriculares estan en el campus?", intent: "extracurriculares" },
    { question: "actividades extracurriculares en el campus?", intent: "extracurriculares" },
    { question: "hay alguna actividad interesante para el fin de semana?", intent: "eventoFinde" },
    { question: "actividades interesantes para el fin de semana?", intent: "eventoFinde" },
    { question: "eventos interesantes para el fin de semana?", intent: "eventoFinde" },
    { question: "que hay para el fin de semana en el campus?", intent: "eventoFinde" },
    { question: "opciones de alimentacion disponibles en el campus?", intent: "alimentacion" },
    { question: "donde puedo comer en el campus?", intent: "alimentacion" },
    { question: "que lugares para comer hay en el campus?", intent: "alimentacion" },
    { question: "donde encontrar comida en el campus?", intent: "alimentacion" },
    { question: "donde se puede comer en el campus?", intent: "alimentacion" },
    { question: "cuando es la fecha de inscripcion de cursos?", intent: "fechaInscripcion" },
    { question: "fecha inscripcion cursos?", intent: "fechaInscripcion" },
    { question: "cuándo son las inscripciones?", intent: "fechaInscripcion" },
    { question: "donde conseguir pasantias?", intent: "pasantias" },
    { question: "donde hay pasantias?", intent: "pasantias" },
    { question: "donde hallar pasantias?", intent: "pasantias" },
    { question: "donde encontrar practicas?", intent: "pasantias" },
    { question: "practicas profesionales en el campus?", intent: "pasantias" },
    { question: "clubes y actividades en el campus?", intent: "extracurriculares" },
    { question: "clubes disponibles en el campus?", intent: "extracurriculares" },
    { question: "actividades extracurriculares en el campus?", intent: "extracurriculares" },
    { question: "hay actividades interesantes para el fin de semana?", intent: "eventoFinde" },
    { question: "actividades para el fin de semana?", intent: "eventoFinde" },
    { question: "eventos del fin de semana en el campus?", intent: "eventoFinde" },
    { question: "opciones de comida en el campus?", intent: "alimentacion" },
    { question: "donde puedo comer en el campus?", intent: "alimentacion" },
    { question: "lugares para comer en el campus?", intent: "alimentacion" },
    { question: "opciones de alimentacion en el campus?", intent: "alimentacion" },
    { question: "¿cuándo es la inscripción de cursos?", intent: "fechaInscripcion" },
    { question: "¿cuándo empieza la inscripción de cursos?", intent: "fechaInscripcion" },
    { question: "¿dónde están las pasantías disponibles?", intent: "pasantias" },
    { question: "¿dónde encontrar pasantías profesionales?", intent: "pasantias" },
    { question: "¿dónde están las prácticas profesionales disponibles?", intent: "pasantias" },
    { question: "¿qué clubes existen en el campus?", intent: "extracurriculares" },
    { question: "¿cuáles son los clubes y actividades extracurriculares disponibles?", intent: "extracurriculares" },
    { question: "¿hay eventos interesantes en el fin de semana?", intent: "eventoFinde" },
    { question: "¿qué eventos interesantes hay para el fin de semana?", intent: "eventoFinde" },
    { question: "¿qué opciones de alimentación tengo en el campus?", intent: "alimentacion" },
    { question: "cuando es la fecha de inscripcion?", intent: "fechaInscripcion" },
    { question: "¿Cuál es el calendario académico para este semestre?", intent: "calendarioSemestre" },
    { question: "¿Dónde puedo encontrar mi horario de clases?", intent: "horarioPersonalClase" },
    { question: "¿Cuándo son los períodos de inscripción para cursos?", intent: "fechaInscripcion" },
    { question: "¿Dónde está la biblioteca y cuáles son sus horarios?", intent: "biblioteca" },
    { question: "¿Cómo puedo contactar al departamento de servicios estudiantiles?", intent: "contactoServiciosEstudiantiles" },
    { question: "¿Hay algún evento importante en el campus esta semana?", intent: "semanaEvento" },
    { question: "¿Dónde puedo obtener ayuda si estoy experimentando estrés o problemas emocionales?", intent: "ayudaEmocional" },
    { question: "¿Cuáles son los recursos disponibles para estudiantes con discapacidades?", intent: "recursosDiscapacidad" },
    { question: "¿Qué servicios de asesoramiento o tutoría están disponibles para mejorar mi rendimiento académico?", intent: "tutoriaAcademica" },
    { question: "¿Cómo puedo encontrar pasantías o prácticas profesionales relevantes para mi carrera?", intent: "pasantias" },
    { question: "¿Qué recursos ofrece la universidad para ayudarme a escribir mi currículum vitae?", intent: "curriculumRecursos" },
    { question: "¿Hay talleres disponibles para prepararme para entrevistas de trabajo?", intent: "talleresEntrevistas" },
    { question: "¿Cuál es el calendario académico para este semestre?", intent: "calendarioSemestre" },
    { question: "Calendario académico del semestre?", intent: "calendarioSemestre" },
    { question: "calendario academico semestre?", intent: "calendarioSemestre" },
    { question: "calendario academico semestre", intent: "calendarioSemestre" },
    { question: "¿Dónde veo mi horario de clases?", intent: "horarioPersonalClase" },
    { question: "Horario de mis clases?", intent: "horarioPersonalClase" },
    { question: "¿Dónde veo mi horario?", intent: "horarioPersonalClase" },
    { question: "mi horario", intent: "horarioPersonalClase" },
    { question: "¿Cuándo empieza la inscripción de cursos?", intent: "fechaInscripcion" },
    { question: "Fecha de inscripción de cursos?", intent: "fechaInscripcion" },
    { question: "¿Cuándo inscribo los cursos?", intent: "fechaInscripcion" },
    { question: "cuando inscribo", intent: "fechaInscripcion" },
    { question: "¿Dónde está la biblioteca?", intent: "biblioteca" },
    { question: "¿Horarios de la biblioteca?", intent: "biblioteca" },
    { question: "¿Dónde está la biblioteca y sus horarios?", intent: "biblioteca" },
    { question: "¿Cómo contacto a servicios estudiantiles?", intent: "contactoServiciosEstudiantiles" },
    { question: "Contacto servicios estudiantiles?", intent: "contactoServiciosEstudiantiles" },
    { question: "¿Cómo hablar con servicios estudiantiles?", intent: "contactoServiciosEstudiantiles" },
    { question: "como hablar con servicios estudiantiles", intent: "contactoServiciosEstudiantiles" },
    { question: "Eventos importantes en el campus?", intent: "semanaEvento" },
    { question: "Eventos en el campus esta semana?", intent: "semanaEvento" },
    { question: "¿Hay eventos importantes en el campus esta semana?", intent: "semanaEvento" },
    { question: "eventos importantes esta semana", intent: "semanaEvento" },
    { question: "Ayuda con estrés o problemas emocionales?", intent: "ayudaEmocional" },
    { question: "¿Dónde puedo obtener ayuda para el estrés?", intent: "ayudaEmocional" },
    { question: "¿Ayuda con problemas emocionales?", intent: "ayudaEmocional" },
    { question: "Ayuda emocional", intent: "ayudaEmocional" },
    { question: "Recursos para estudiantes con discapacidades?", intent: "recursosDiscapacidad" },
    { question: "¿Recursos disponibles para discapacitados?", intent: "recursosDiscapacidad" },
    { question: "¿Ayuda para estudiantes con discapacidades?", intent: "recursosDiscapacidad" },
    { question: "Ayuda para estudiantes discapacidades", intent: "recursosDiscapacidad" },
    { question: "Servicios de tutoría disponibles?", intent: "tutoriaAcademica" },
    { question: "¿Qué servicios de tutoría hay?", intent: "tutoriaAcademica" },
    { question: "¿Tutoría disponible?", intent: "tutoriaAcademica" },
    { question: "Tutoria disponible", intent: "tutoriaAcademica" },
    { question: "¿Dónde encuentro pasantías?", intent: "pasantias" },
    { question: "Pasantías y prácticas profesionales?", intent: "pasantias" },
    { question: "¿Cómo conseguir una pasantía?", intent: "pasantias" },
    { question: "pasantias", intent: "pasantias" },
    { question: "Recursos para currículum vitae?", intent: "curriculumRecursos" },
    { question: "Ayuda para escribir mi currículum?", intent: "curriculumRecursos" },
    { question: "¿Dónde encuentro ayuda para mi CV?", intent: "curriculumRecursos" },
    { question: "ayuda para mi CV", intent: "curriculumRecursos" },
    { question: "Talleres para entrevistas de trabajo?", intent: "talleresEntrevistas" },
    { question: "¿Hay talleres para entrevistas?", intent: "talleresEntrevistas" },
    { question: "Preparación para entrevistas de trabajo?", intent: "talleresEntrevistas" },
    { question: "Preparacion para entrevistas", intent: "talleresEntrevistas" },
    { question: "¿Dónde veo el calendario académico para este semestre?", intent: "calendarioSemestre" },
    { question: "Dónde puedo ver mi horario de clases?", intent: "horarioPersonalClase" },
    { question: "¿Cuándo son los periodos de inscripción para cursos?", intent: "fechaInscripcion" },
    { question: "¿Dónde está la biblioteca y cuales son sus horarios?", intent: "biblioteca" },
    { question: "Cómo puedo contactar al departamento de servicios estudiantiles?", intent: "contactoServiciosEstudiantiles" },
    { question: "Hay algún evento importante en el campus esta semana?", intent: "semanaEvento" },
    { question: "¿Dónde puedo obtener ayuda si estoy experimentando estrés o problemas emocionales?", intent: "ayudaEmocional" },
    { question: "Cuáles son los recursos disponibles para estudiantes con discapacidades?", intent: "recursosDiscapacidad" },
    { question: "Qué servicios de asesoramiento o tutoría están disponibles para mejorar mi rendimiento académico?", intent: "tutoriaAcademica" },
    { question: "Cómo puedo encontrar pasantías o prácticas profesionales relevantes para mi carrera?", intent: "pasantias" },
    { question: "Qué recursos ofrece la universidad para ayudarme a escribir mi currículum vitae?", intent: "curriculumRecursos" },
    { question: "Hay talleres disponibles para prepararme para entrevistas de trabajo?", intent: "talleresEntrevistas" },
    { question: "Cuál es el calendario académico para este semestre?", intent: "calendarioSemestre" },
    { question: "calendario academico del semestre?", intent: "calendarioSemestre" },
    { question: "calendario academico de este semestre?", intent: "calendarioSemestre" },
    { question: "Dónde veo el horario de mis clases?", intent: "horarioPersonalClase" },
    { question: "el horario de mis clases?", intent: "horarioPersonalClase" },
    { question: "Dónde veo mi horario de clases?", intent: "horarioPersonalClase" },
    { question: "Cuando empieza la inscripción de cursos?", intent: "fechaInscripcion" },
    { question: "fecha de inscripción de cursos?", intent: "fechaInscripcion" },
    { question: "cuando inscribo los cursos?", intent: "fechaInscripcion" },
    { question: "Dónde está la biblioteca?", intent: "biblioteca" },
    { question: "los Horarios de la biblioteca?", intent: "biblioteca" },
    { question: "Dónde está la biblioteca y sus horarios?", intent: "biblioteca" },
    { question: "Cómo contacto a servicios estudiantiles?", intent: "contactoServiciosEstudiantiles" },
    { question: "el Contacto servicios estudiantiles?", intent: "contactoServiciosEstudiantiles" },
    { question: "Cómo hablar con servicios estudiantiles?", intent: "contactoServiciosEstudiantiles" },
    { question: "Eventos importantes en el campus?", intent: "semanaEvento" },
    { question: "los Eventos en el campus esta semana?", intent: "semanaEvento" },
    { question: "Hay eventos importantes en el campus esta semana?", intent: "semanaEvento" },
    { question: "la Ayuda con estrés o problemas emocionales?", intent: "ayudaEmocional" },
    { question: "Dónde puedo obtener ayuda para el estrés?", intent: "ayudaEmocional" },
    { question: "la Ayuda con problemas emocionales?", intent: "ayudaEmocional" },
    { question: "Recursos para estudiantes con discapacidades?", intent: "recursosDiscapacidad" },
    { question: "los Recursos disponibles para discapacitados?", intent: "recursosDiscapacidad" },
    { question: "la Ayuda para estudiantes con discapacidades?", intent: "recursosDiscapacidad" },
    { question: "los Servicios de tutoría disponibles?", intent: "tutoriaAcademica" },
    { question: "Qué servicios de tutoría hay?", intent: "tutoriaAcademica" },
    { question: "Tutoría disponible?", intent: "tutoriaAcademica" },
    { question: "Dónde encuentro pasantías?", intent: "pasantias" },
    { question: "Pasantías y prácticas profesionales?", intent: "pasantias" },
    { question: "Cómo conseguir una pasantía?", intent: "pasantias" },
    { question: "Recursos para currículum vitae?", intent: "curriculumRecursos" },
    { question: "la Ayuda para escribir mi currículum?", intent: "curriculumRecursos" },
    { question: "Dónde encuentro ayuda para mi CV?", intent: "curriculumRecursos" },
    { question: "¿hay eventos interesantes en el fin de semana?", intent: "eventoFinde" },
    { question: "cuando es la fecha de inscripcion?", intent: "fechaInscripcion" },
    { question: "cuando es la fecha inscripcion?", intent: "fechaInscripcion" },
    { question: "cuando inscripcion cursos?", intent: "fechaInscripcion" },
    { question: "donde puedo encontrar pasantias?", intent: "pasantias" },
    { question: "donde encontrar pasantias?", intent: "pasantias" },
    { question: "donde estan las pasantias?", intent: "pasantias" },
    { question: "donde encontrar practicas profesionales?", intent: "pasantias" },
    { question: "donde estan las practicas profesionales?", intent: "pasantias" },
    { question: "practicas profesionales disponibles?", intent: "pasantias" },
    { question: "practicas profesionales disponibles en el campus?", intent: "pasantias" },  
    { question: "practicas profesionales en el campus?", intent: "pasantias" },
    { question: "pasantias en el campus?", intent: "pasantias" },
    { question: "¿dónde puedo ver las prácticas profesionales?", intent: "pasantias" },
    { question: "dónde puedo ver las prácticas profesionales?", intent: "pasantias" },
    { question: "dónde puedo ver las prácticas profesionales", intent: "pasantias" },
    { question: "donde puedo ver las practicas profesionales?", intent: "pasantias" },
    { question: "¿practicas profesionales en el campus?", intent: "pasantias" },
    { question: "que clubes hay en el campus?", intent: "extracurriculares" },
    { question: "que clubes existen en el campus?", intent: "extracurriculares" },
    { question: "que actividades extracurriculares hay en el campus?", intent: "extracurriculares" },
    { question: "que clubes o actividades extracurriculares estan en el campus?", intent: "extracurriculares" },
    { question: "actividades extracurriculares en el campus?", intent: "extracurriculares" },
    { question: "hay alguna actividad interesante para el fin de semana?", intent: "eventoFinde" },
    { question: "actividades interesantes para el fin de semana?", intent: "eventoFinde" },
    { question: "eventos interesantes para el fin de semana?", intent: "eventoFinde" },
    { question: "que hay para el fin de semana en el campus?", intent: "eventoFinde" },
    { question: "opciones de alimentacion disponibles en el campus?", intent: "alimentacion" },
    { question: "donde puedo comer en el campus?", intent: "alimentacion" },
    { question: "que lugares para comer hay en el campus?", intent: "alimentacion" },
    { question: "donde encontrar comida en el campus?", intent: "alimentacion" },
    { question: "donde se puede comer en el campus?", intent: "alimentacion" },
    
    // Variaciones adicionales
    { question: "¿cuando es la inscripcion?", intent: "fechaInscripcion" },
    { question: "¿cuando empieza la inscripcion?", intent: "fechaInscripcion" },
    { question: "¿cuándo son las inscripciones de cursos?", intent: "fechaInscripcion" },
    { question: "donde encontrar pasantias?", intent: "pasantias" },
    { question: "¿donde están las pasantías?", intent: "pasantias" },
    { question: "¿donde buscar practicas profesionales?", intent: "pasantias" },
    { question: "¿dónde puedo ver las prácticas profesionales?", intent: "pasantias" },
    { question: "¿qué clubs hay en el campus?", intent: "extracurriculares" },
    { question: "¿qué clubes extracurriculares existen en el campus?", intent: "extracurriculares" },
    { question: "¿cuáles son las actividades extracurriculares en el campus?", intent: "extracurriculares" },
    { question: "¿hay clubes disponibles en el campus?", intent: "extracurriculares" },
    { question: "¿qué eventos interesantes hay esta semana?", intent: "semanaEvento" },
    { question: "¿hay actividades para el fin de semana en el campus?", intent: "eventoFinde" },
    { question: "¿qué opciones de alimentación hay en el campus?", intent: "alimentacion" },
    { question: "¿dónde hay comida en el campus?", intent: "alimentacion" },
    { question: "¿cuáles son los lugares para comer en el campus?", intent: "alimentacion" },
    
    // Más variaciones
    { question: "¿cuándo son las fechas de inscripción de cursos?", intent: "fechaInscripcion" },
    { question: "¿dónde están las prácticas profesionales disponibles?", intent: "pasantias" },
    { question: "¿qué actividades extracurriculares hay en el campus?", intent: "extracurriculares" },
    { question: "¿qué eventos hay para el fin de semana en el campus?", intent: "eventoFinde" },
    { question: "¿dónde comer en el campus?", intent: "alimentacion" },
    { question: "¿dónde puedo encontrar pasantías o prácticas profesionales?", intent: "pasantias" },
    { question: "¿qué recursos hay para estudiantes con discapacidades en el campus?", intent: "recursosDiscapacidad" },
    { question: "¿dónde encontrar tutorías académicas en el campus?", intent: "tutoriaAcademica" },
    { question: "¿cuándo es el período de inscripción para cursos en el campus?", intent: "fechaInscripcion" },
    { question: "¿dónde están los clubes extracurriculares en el campus?", intent: "extracurriculares" },
    { question: "¿hay algún evento planeado para el fin de semana en el campus?", intent: "eventoFinde" },
    { question: "¿cuáles son las opciones de comida en el campus?", intent: "alimentacion" },
    { question: "los Talleres para entrevistas de trabajo?", intent: "talleresEntrevistas" },
    { question: "Hay talleres para entrevistas?", intent: "talleresEntrevistas" },
    { question: "la Preparación para entrevistas de trabajo?", intent: "talleresEntrevistas" },
    { question: "calendario académico de la universidad?", intent: "calendarioSemestre" },
    { question: "horario de clases de este semestre?", intent: "horarioPersonalClase" },
    { question: "fechas de inscripción para nuevos cursos?", intent: "fechaInscripcion" },
    { question: "dónde está ubicada la biblioteca central?", intent: "biblioteca" },
    { question: "número de contacto del departamento de servicios estudiantiles?", intent: "contactoServiciosEstudiantiles" },
    { question: "algún evento relevante en el campus esta semana?", intent: "semanaEvento" },
    { question: "cómo puedo obtener apoyo emocional?", intent: "ayudaEmocional" },
    { question: "qué recursos hay para estudiantes con necesidades especiales?", intent: "recursosDiscapacidad" },
    { question: "hay tutorías disponibles para estudiantes?", intent: "tutoriaAcademica" },
    { question: "dónde puedo buscar pasantías?", intent: "pasantias" },
    { question: "qué ayuda ofrece la universidad para crear un currículum?", intent: "curriculumRecursos" },
    { question: "hay talleres de preparación para entrevistas laborales?", intent: "talleresEntrevistas" },
    { question: "puedo ver el calendario académico en línea?", intent: "calendarioSemestre" },
    { question: "dónde encontrar mi horario de clase?", intent: "horarioPersonalClase" },
    { question: "cuáles son las fechas de inscripción?", intent: "fechaInscripcion" },
    { question: "la biblioteca está abierta los fines de semana?", intent: "biblioteca" },
    { question: "cómo contactar servicios estudiantiles por correo electrónico?", intent: "contactoServiciosEstudiantiles" },
    { question: "qué eventos se realizan en el campus esta semana?", intent: "semanaEvento" },
    { question: "¿dónde recibir ayuda para problemas de estrés?", intent: "ayudaEmocional" },
    { question: "¿la universidad ofrece apoyo a estudiantes con discapacidades?", intent: "recursosDiscapacidad" },
    { question: "¿dónde puedo recibir asesoría académica?", intent: "tutoriaAcademica" },
    { question: "¿cómo acceder a ofertas de pasantías?", intent: "pasantias" },
    { question: "¿qué recursos hay para mejorar mi currículum?", intent: "curriculumRecursos" },
    { question: "¿hay talleres para preparar entrevistas de trabajo?", intent: "talleresEntrevistas" },
    { question: "¿cómo consultar el calendario académico?", intent: "calendarioSemestre" },
    { question: "¿dónde veo mi horario de este semestre?", intent: "horarioPersonalClase" },
    { question: "¿cuáles son los periodos de inscripción?", intent: "fechaInscripcion" },
    { question: "¿la biblioteca tiene servicio nocturno?", intent: "biblioteca" },
    { question: "¿cómo contactar servicios estudiantiles por teléfono?", intent: "contactoServiciosEstudiantiles" },
    { question: "¿hay eventos esta semana en el campus?", intent: "semanaEvento" },
    { question: "¿dónde obtener apoyo para problemas emocionales?", intent: "ayudaEmocional" },
    { question: "qué apoyo se da a estudiantes con discapacidades?", intent: "recursosDiscapacidad" },
    { question: "hay asesoría académica disponible?", intent: "tutoriaAcademica" },
    { question: "dónde buscar pasantías para mi carrera?", intent: "pasantias" },
    { question: "cómo mejorar mi currículum con los recursos de la universidad?", intent: "curriculumRecursos" },
    { question: "dónde hay talleres para entrevistas laborales?", intent: "talleresEntrevistas" },
    { question: "el calendario académico está disponible en línea?", intent: "calendarioSemestre" },
    { question: "cómo ver mi horario de clases?", intent: "horarioPersonalClase" },
    { question: "cuáles son las fechas importantes de inscripción?", intent: "fechaInscripcion" },
    { question: "la biblioteca tiene horarios extendidos?", intent: "biblioteca" },
    { question: "cómo contacto al departamento de servicios estudiantiles?", intent: "contactoServiciosEstudiantiles" },
    { question: "qué eventos hay en el campus esta semana?", intent: "semanaEvento" },
    { question: "dónde recibir ayuda emocional?", intent: "ayudaEmocional" },
    { question: "¿hay recursos para estudiantes con discapacidades?", intent: "recursosDiscapacidad" },
    { question: "¿dónde recibir asesoría académica?", intent: "tutoriaAcademica" },
    { question: "¿cómo encontrar pasantías?", intent: "pasantias" },
    { question: "¿qué recursos hay para currículum vitae?", intent: "curriculumRecursos" },
    { question: "¿dónde prepararme para entrevistas de trabajo?", intent: "talleresEntrevistas" },
    { question: "¿calendario académico actual?", intent: "calendarioSemestre" },
    { question: "¿horario de clases disponible?", intent: "horarioPersonalClase" },
    { question: "¿fechas de inscripción a la vista?", intent: "fechaInscripcion" },
    { question: "¿dónde está la biblioteca?", intent: "biblioteca" },
    { question: "¿contacto de servicios estudiantiles?", intent: "contactoServiciosEstudiantiles" },
    { question: "¿eventos en el campus esta semana?", intent: "semanaEvento" },
    { question: "¿ayuda para el estrés disponible?", intent: "ayudaEmocional" },
    { question: "¿apoyo a discapacitados?", intent: "recursosDiscapacidad" },
    // Variaciones para "¿Cuál es el calendario académico para este semestre?"
    { question: "¿Cómo puedo ver el calendario académico de este semestre?", intent: "calendarioSemestre" },
    { question: "¿Qué fechas importantes hay en el calendario académico de este semestre?", intent: "calendarioSemestre" },
    { question: "¿Dónde encuentro el calendario académico para este semestre?", intent: "calendarioSemestre" },
    { question: "¿Calendario académico de este semestre?", intent: "calendarioSemestre" },
    { question: "¿Cuáles son las fechas del calendario académico para el semestre actual?", intent: "calendarioSemestre" },

    // Variaciones para "¿Dónde puedo encontrar mi horario de clases?"
    { question: "¿Dónde está mi horario de clases?", intent: "horarioPersonalClase" },
    { question: "¿Cómo encuentro mi horario de clases?", intent: "horarioPersonalClase" },
    { question: "¿Dónde puedo ver el horario de clases?", intent: "horarioPersonalClase" },
    { question: "¿Dónde está disponible mi horario de clases?", intent: "horarioPersonalClase" },
    { question: "¿Cómo puedo acceder a mi horario de clases?", intent: "horarioPersonalClase" },

    // Variaciones para "¿Cuándo son los períodos de inscripción para cursos?"
    { question: "¿Cuáles son las fechas de inscripción para cursos?", intent: "fechaInscripcion" },
    { question: "¿Cuándo empieza la inscripción para cursos?", intent: "fechaInscripcion" },
    { question: "¿Qué días son los períodos de inscripción para cursos?", intent: "fechaInscripcion" },
    { question: "¿Qué fechas están disponibles para inscribirse en los cursos?", intent: "fechaInscripcion" },
    { question: "¿Cuándo es el período de inscripción para los cursos?", intent: "fechaInscripcion" },

    // Variaciones para "¿Dónde está la biblioteca y cuáles son sus horarios?"
    { question: "¿Dónde se encuentra la biblioteca y cuáles son sus horarios de apertura?", intent: "biblioteca" },
    { question: "¿Dónde está ubicada la biblioteca y qué horarios tiene?", intent: "biblioteca" },
    { question: "¿Dónde está la biblioteca y qué horarios tiene durante la semana?", intent: "biblioteca" },
    { question: "¿Qué horario tiene la biblioteca y dónde está?", intent: "biblioteca" },
    { question: "¿Dónde encontrar la biblioteca y sus horarios?", intent: "biblioteca" },

    // Variaciones para "¿Cómo puedo contactar al departamento de servicios estudiantiles?"
    { question: "¿Cómo contactar con el departamento de servicios estudiantiles?", intent: "contactoServiciosEstudiantiles" },
    { question: "¿Cuál es el contacto para servicios estudiantiles?", intent: "contactoServiciosEstudiantiles" },
    { question: "¿Dónde encuentro el contacto del departamento de servicios estudiantiles?", intent: "contactoServiciosEstudiantiles" },
    { question: "¿Cómo me comunico con el departamento de servicios estudiantiles?", intent: "contactoServiciosEstudiantiles" },
    { question: "¿Cuál es la forma de contacto para el departamento de servicios estudiantiles?", intent: "contactoServiciosEstudiantiles" },
    { question: "Cómo contactar con el departamento de servicios estudiantiles?", intent: "contactoServiciosEstudiantiles" },
    { question: "Cuál es el contacto para servicios estudiantiles?", intent: "contactoServiciosEstudiantiles" },
    { question: "Dónde encuentro el contacto del departamento de servicios estudiantiles?", intent: "contactoServiciosEstudiantiles" },
    { question: "Cómo me comunico con el departamento de servicios estudiantiles?", intent: "contactoServiciosEstudiantiles" },
    { question: "Cuál es la forma de contacto para el departamento de servicios estudiantiles?", intent: "contactoServiciosEstudiantiles" },
    { question: "Cómo contactar con el departamento de servicios estudiantiles", intent: "contactoServiciosEstudiantiles" },
    { question: "Cuál es el contacto para servicios estudiantiles", intent: "contactoServiciosEstudiantiles" },
    { question: "Dónde encuentro el contacto del departamento de servicios estudiantiles", intent: "contactoServiciosEstudiantiles" },
    { question: "Cómo me comunico con el departamento de servicios estudiantiles", intent: "contactoServiciosEstudiantiles" },
    { question: "Cuál es la forma de contacto para el departamento de servicios estudiantiles", intent: "contactoServiciosEstudiantiles" },

    // Variaciones para "¿Hay algún evento importante en el campus esta semana?"
    { question: "¿Qué eventos importantes hay en el campus esta semana?", intent: "semanaEvento" },
    { question: "¿Hay eventos destacables en el campus esta semana?", intent: "semanaEvento" },
    { question: "¿Qué actividades importantes están planeadas para esta semana en el campus?", intent: "semanaEvento" },
    { question: "¿Eventos relevantes en el campus esta semana?", intent: "semanaEvento" },
    { question: "¿Hay algún evento significativo en el campus para esta semana?", intent: "semanaEvento" },

    // Variaciones para "¿Dónde puedo obtener ayuda si estoy experimentando estrés o problemas emocionales?"
    { question: "¿Dónde encontrar ayuda para estrés o problemas emocionales?", intent: "ayudaEmocional" },
    { question: "¿Cómo puedo obtener ayuda si tengo problemas emocionales en el campus?", intent: "ayudaEmocional" },
    { question: "¿Dónde recibir apoyo emocional si estoy estresado?", intent: "ayudaEmocional" },
    { question: "¿Dónde buscar ayuda para problemas de estrés o emocionales?", intent: "ayudaEmocional" },
    { question: "¿Qué recursos están disponibles para problemas emocionales en el campus?", intent: "ayudaEmocional" },

    // Variaciones para "¿Cuáles son los recursos disponibles para estudiantes con discapacidades?"
    { question: "¿Qué recursos hay para estudiantes con discapacidades en el campus?", intent: "recursosDiscapacidad" },
    { question: "¿Cuáles son los apoyos para estudiantes con discapacidades?", intent: "recursosDiscapacidad" },
    { question: "¿Dónde encontrar recursos para estudiantes con discapacidades?", intent: "recursosDiscapacidad" },
    { question: "¿Qué ayuda está disponible para estudiantes con discapacidades?", intent: "recursosDiscapacidad" },
    { question: "¿Cuáles son los recursos de apoyo para estudiantes con discapacidades?", intent: "recursosDiscapacidad" },

    // Variaciones para "¿Qué servicios de asesoramiento o tutoría están disponibles para mejorar mi rendimiento académico?"
    { question: "¿Qué servicios de tutoría académica están disponibles?", intent: "tutoriaAcademica" },
    { question: "¿Dónde puedo encontrar asesoramiento académico para mejorar mi rendimiento?", intent: "tutoriaAcademica" },
    { question: "¿Qué tipo de asesoramiento académico se ofrece para mejorar el rendimiento?", intent: "tutoriaAcademica" },
    { question: "¿Qué opciones de tutoría están disponibles para estudiantes?", intent: "tutoriaAcademica" },
    { question: "¿Dónde puedo recibir asesoría para mejorar mi rendimiento académico?", intent: "tutoriaAcademica" },

    // Variaciones para "¿Cómo puedo encontrar pasantías o prácticas profesionales relevantes para mi carrera?"
    { question: "¿Dónde buscar pasantías o prácticas profesionales para mi carrera?", intent: "pasantias" },
    { question: "¿Cómo encuentro pasantías relevantes para mi carrera profesional?", intent: "pasantias" },
    { question: "¿Dónde están disponibles pasantías para mi carrera?", intent: "pasantias" },
    { question: "¿Dónde encontrar prácticas profesionales relacionadas con mi carrera?", intent: "pasantias" },
    { question: "¿Cómo acceder a pasantías relevantes para mi área de estudio?", intent: "pasantias" },   
    { question: "Dónde buscar pasantías o prácticas profesionales para mi carrera?", intent: "pasantias" },
    { question: "Cómo encuentro pasantías relevantes para mi carrera profesional?", intent: "pasantias" },
    { question: "Dónde están disponibles pasantías para mi carrera?", intent: "pasantias" },
    { question: "Dónde encontrar prácticas profesionales relacionadas con mi carrera?", intent: "pasantias" },
    { question: "Cómo acceder a pasantías relevantes para mi área de estudio?", intent: "pasantias" },
    { question: "Dónde buscar pasantías o prácticas profesionales para mi carrera", intent: "pasantias" },
    { question: "Cómo encuentro pasantías relevantes para mi carrera profesional", intent: "pasantias" },
    { question: "Dónde están disponibles pasantías para mi carrera", intent: "pasantias" },
    { question: "Dónde encontrar prácticas profesionales relacionadas con mi carrera", intent: "pasantias" },
    { question: "Cómo acceder a pasantías relevantes para mi área de estudio", intent: "pasantias" },
    //
    { question: "¿Dónde puedo encontrar clubes y actividades extracurriculares?", intent: "extracurriculares" },
    { question: "Dónde puedo encontrar clubes y actividades extracurriculares?", intent: "extracurriculares" },
    { question: "Dónde puedo encontrar clubes y actividades extracurriculares", intent: "extracurriculares" },
    { question: "Donde puedo encontrar clubes y actividades extracurriculares", intent: "extracurriculares" },
    //
    { question: "¿Cómo acceder a pasantías relevantes para mi área de estudio?", intent: "pasantias" },
    { question: "Cómo acceder a pasantías relevantes para mi área de estudio?", intent: "pasantias" },
    { question: "Cómo acceder a pasantías relevantes para mi área de estudio", intent: "pasantias" },
    { question: "Como acceder a pasantías relevantes para mi área de estudio", intent: "pasantias" },
    //
    { question: "¿Cómo encuentro pasantías relevantes para mi carrera profesional?", intent: "pasantias" },
    { question: "Cómo encuentro pasantías relevantes para mi carrera profesional?", intent: "pasantias" },
    { question: "Cómo encuentro pasantías relevantes para mi carrera profesional", intent: "pasantias" },
    { question: "Como encuentro pasantías relevantes para mi carrera profesional", intent: "pasantias" },
    //
    { question: "¿Qué tipo de asesoramiento académico se ofrece para mejorar el rendimiento?", intent: "tutoriaAcademica" },
    { question: "Qué tipo de asesoramiento académico se ofrece para mejorar el rendimiento", intent: "tutoriaAcademica" },
    { question: "Qué tipo de asesoramiento académico se ofrece para mejorar el rendimiento?", intent: "tutoriaAcademica" },
    { question: "Que tipo de asesoramiento académico se ofrece para mejorar el rendimiento", intent: "tutoriaAcademica" },
    //
    { question: "Qué fechas están disponibles para inscribirse en los cursos?", intent: "fechaInscripcion" },
    { question: "Que fechas están disponibles para inscribirse en los cursos?", intent: "fechaInscripcion" },
    { question: "fechas disponibles para inscribirse en los cursos", intent: "fechaInscripcion" },
    //
    { question: "¿asesoría académica?", intent: "tutoriaAcademica" },
    { question: "¿pasantías disponibles?", intent: "pasantias" },
    { question: "¿recursos para currículum vitae?", intent: "curriculumRecursos" },
    { question: "¿talleres de entrevistas de trabajo?", intent: "talleresEntrevistas" },
    { question: "¿calendario académico del semestre?", intent: "calendarioSemestre" },
    { question: "¿horario de clases del semestre?", intent: "horarioPersonalClase" },
    { question: "fechas de inscripción de cursos?", intent: "fechaInscripcion" },
    { question: "ubicación de la biblioteca?", intent: "biblioteca" },
    { question: "contacto del departamento de servicios estudiantiles?", intent: "contactoServiciosEstudiantiles" },
    { question: "eventos importantes esta semana en el campus?", intent: "semanaEvento" },
    { question: "dónde obtener ayuda emocional?", intent: "ayudaEmocional" },
    { question: "recursos para estudiantes discapacitados?", intent: "recursosDiscapacidad" },
    { question: "asesoramiento académico disponible?", intent: "tutoriaAcademica" },
    { question: "cómo encontrar prácticas profesionales?", intent: "pasantias" },
    { question: "ayuda para escribir mi currículum vitae?", intent: "curriculumRecursos" },
    { question: "talleres de preparación para entrevistas?", intent: "talleresEntrevistas" },
    { question: "¿dónde ver el calendario académico?", intent: "calendarioSemestre" },
    { question: "¿cómo consultar mi horario de clases?", intent: "horarioPersonalClase" },
    { question: "¿cuáles son las fechas de inscripción a cursos?", intent: "fechaInscripcion" },
    { question: "¿la biblioteca está abierta los fines de semana?", intent: "biblioteca" },
    { question: "¿cómo contactar servicios estudiantiles por teléfono?", intent: "contactoServiciosEstudiantiles" },
    { question: "¿eventos importantes en el campus esta semana?", intent: "semanaEvento" },
    { question: "¿dónde obtener apoyo para problemas emocionales?", intent: "ayudaEmocional" },
    { question: "¿qué apoyo se ofrece a estudiantes con discapacidades?", intent: "recursosDiscapacidad" },
    { question: "¿dónde recibir asesoría académica?", intent: "tutoriaAcademica" },
    { question: "¿dónde buscar pasantías relevantes para mi carrera?", intent: "pasantias" },
    { question: "¿cómo mejorar mi currículum vitae?", intent: "curriculumRecursos" },
    { question: "¿talleres para entrevistas de trabajo disponibles?", intent: "talleresEntrevistas" },
    { question: "¿calendario académico de este semestre?", intent: "calendarioSemestre" },
    { question: "¿dónde está mi horario de clases?", intent: "horarioPersonalClase" },
    { question: "¿cuáles son las fechas de inscripción para cursos?", intent: "fechaInscripcion" },
    { question: "¿horarios de la biblioteca?", intent: "biblioteca" },
    { question: "¿cómo contactar a servicios estudiantiles?", intent: "contactoServiciosEstudiantiles" },
    { question: "¿eventos en el campus esta semana?", intent: "semanaEvento" },
    { question: "¿dónde puedo obtener ayuda emocional?", intent: "ayudaEmocional" },
    { question: "¿recursos disponibles para estudiantes con discapacidades?", intent: "recursosDiscapacidad" },
    { question: "¿asesoría académica disponible?", intent: "tutoriaAcademica" },
    { question: "¿cómo encontrar pasantías?", intent: "pasantias" },
    { question: "recursos para mejorar mi currículum vitae?", intent: "curriculumRecursos" },
    { question: "talleres de preparación para entrevistas laborales?", intent: "talleresEntrevistas" },
    { question: "dónde consultar el calendario académico?", intent: "calendarioSemestre" },
    { question: "cómo ver mi horario de clases?", intent: "horarioPersonalClase" },
    { question: "cuáles son las fechas de inscripción de cursos?", intent: "fechaInscripcion" },
    { question: "la biblioteca está abierta los fines de semana?", intent: "biblioteca" },
    { question: "cómo contactar servicios estudiantiles?", intent: "contactoServiciosEstudiantiles" },
    { question: "eventos en el campus esta semana?", intent: "semanaEvento" },
    { question: "dónde recibir ayuda para problemas emocionales?", intent: "ayudaEmocional" },
    { question: "¿qué recursos hay para estudiantes con discapacidades?", intent: "recursosDiscapacidad" },
    { question: "¿dónde recibir asesoramiento académico?", intent: "tutoriaAcademica" },
    { question: "¿cómo encontrar pasantías y prácticas profesionales?", intent: "pasantias" },
    { question: "¿recursos para escribir mi currículum vitae?", intent: "curriculumRecursos" },
    { question: "¿talleres de entrevistas de trabajo disponibles?", intent: "talleresEntrevistas" },
    { question: "cuando inscripcion cursos?", intent: "fechaInscripcion" },
    { question: "donde estan las pasantias?", intent: "pasantias" },
    { question: "donde encontrar practicas profesionales?", intent: "pasantias" },
    { question: "que clubes hay en el campus?", intent: "extracurriculares" },
    { question: "actividades extracurriculares en el campus?", intent: "extracurriculares" },
    { question: "hay alguna actividad interesante para el fin de semana?", intent: "eventoFinde" },
    { question: "opciones de alimentacion disponibles en el campus?", intent: "alimentacion" },
    { question: "donde se puede comer en el campus?", intent: "alimentacion" },
    { question: "cuando es la fecha de inscripcion de cursos?", intent: "fechaInscripcion" },
    { question: "donde conseguir pasantias?", intent: "pasantias" },
    { question: "practicas profesionales en el campus?", intent: "pasantias" },
    { question: "actividades extracurriculares en el campus?", intent: "extracurriculares" },
    { question: "hay actividades interesantes para el fin de semana?", intent: "eventoFinde" },
    { question: "actividades para el fin de semana?", intent: "eventoFinde" },
    { question: "eventos del fin de semana en el campus?", intent: "eventoFinde" },
    { question: "lugares para comer en el campus?", intent: "alimentacion" },
    { question: "opciones de alimentacion en el campus?", intent: "alimentacion" },
    { question: "¿cuándo empieza la inscripción de cursos?", intent: "fechaInscripcion" },
    { question: "¿dónde están las pasantías disponibles?", intent: "pasantias" },
    { question: "¿dónde están las prácticas profesionales disponibles?", intent: "pasantias" },
    { question: "¿cuáles son los clubes y actividades extracurriculares disponibles?", intent: "extracurriculares" },
    { question: "¿hay eventos interesantes en el fin de semana?", intent: "eventoFinde" },
    { question: "cuando es la fecha de inscripcion?", intent: "fechaInscripcion" },
    { question: "cuando es la fecha inscripcion?", intent: "fechaInscripcion" },
    { question: "cuando inscripcion cursos?", intent: "fechaInscripcion" },
    { question: "donde puedo encontrar pasantias?", intent: "pasantias" },
    { question: "donde encontrar pasantias?", intent: "pasantias" },
    { question: "donde estan las pasantias?", intent: "pasantias" },
    { question: "donde encontrar practicas profesionales?", intent: "pasantias" },
    { question: "donde estan las practicas profesionales?", intent: "pasantias" },
    { question: "practicas profesionales disponibles?", intent: "pasantias" },
    { question: "que clubes hay en el campus?", intent: "extracurriculares" },
    { question: "que clubes existen en el campus?", intent: "extracurriculares" },
    { question: "que actividades extracurriculares hay en el campus?", intent: "extracurriculares" },
    { question: "que clubes o actividades extracurriculares estan en el campus?", intent: "extracurriculares" },
    { question: "actividades extracurriculares en el campus?", intent: "extracurriculares" },
    { question: "hay alguna actividad interesante para el fin de semana?", intent: "eventoFinde" },
    { question: "actividades interesantes para el fin de semana?", intent: "eventoFinde" },
    { question: "eventos interesantes para el fin de semana?", intent: "eventoFinde" },
    { question: "que hay para el fin de semana en el campus?", intent: "eventoFinde" },
    { question: "opciones de alimentacion disponibles en el campus?", intent: "alimentacion" },
    { question: "donde puedo comer en el campus?", intent: "alimentacion" },
    { question: "que lugares para comer hay en el campus?", intent: "alimentacion" },
    { question: "donde encontrar comida en el campus?", intent: "alimentacion" },
    { question: "donde se puede comer en el campus?", intent: "alimentacion" },
    
    // Variaciones adicionales
    { question: "¿cuando es la inscripcion?", intent: "fechaInscripcion" },
    { question: "¿cuando empieza la inscripcion?", intent: "fechaInscripcion" },
    { question: "¿cuándo son las inscripciones de cursos?", intent: "fechaInscripcion" },
    { question: "donde encontrar pasantias?", intent: "pasantias" },
    { question: "¿donde están las pasantías?", intent: "pasantias" },
    { question: "¿donde buscar practicas profesionales?", intent: "pasantias" },
    { question: "¿dónde puedo ver las prácticas profesionales?", intent: "pasantias" },
    { question: "¿qué clubs hay en el campus?", intent: "extracurriculares" },
    { question: "¿qué clubes extracurriculares existen en el campus?", intent: "extracurriculares" },
    { question: "¿cuáles son las actividades extracurriculares en el campus?", intent: "extracurriculares" },
    { question: "¿hay clubes disponibles en el campus?", intent: "extracurriculares" },
    { question: "¿qué eventos interesantes hay esta semana?", intent: "semanaEvento" },
    { question: "¿hay actividades para el fin de semana en el campus?", intent: "eventoFinde" },
    { question: "¿qué opciones de alimentación hay en el campus?", intent: "alimentacion" },
    { question: "¿dónde hay comida en el campus?", intent: "alimentacion" },
    { question: "¿cuáles son los lugares para comer en el campus?", intent: "alimentacion" },
    
    // Más variaciones
    { question: "¿cuándo son las fechas de inscripción de cursos?", intent: "fechaInscripcion" },
    { question: "¿dónde están las prácticas profesionales disponibles?", intent: "pasantias" },
    { question: "¿qué actividades extracurriculares hay en el campus?", intent: "extracurriculares" },
    { question: "¿qué eventos hay para el fin de semana en el campus?", intent: "eventoFinde" },
    { question: "¿dónde comer en el campus?", intent: "alimentacion" },
    { question: "¿dónde puedo encontrar pasantías o prácticas profesionales?", intent: "pasantias" },
    { question: "¿qué recursos hay para estudiantes con discapacidades en el campus?", intent: "recursosDiscapacidad" },
    { question: "¿dónde encontrar tutorías académicas en el campus?", intent: "tutoriaAcademica" },
    { question: "¿cuándo es el período de inscripción para cursos en el campus?", intent: "fechaInscripcion" },
    { question: "¿dónde están los clubes extracurriculares en el campus?", intent: "extracurriculares" },
    { question: "¿hay algún evento planeado para el fin de semana en el campus?", intent: "eventoFinde" },
    { question: "¿cuáles son las opciones de comida en el campus?", intent: "alimentacion" },
    // Agrega más preguntas e intenciones según sea necesario

    // Variaciones para "¿Cuál es el calendario académico para este semestre?"
    { question: "¿Cómo puedo ver el calendario académico de este semestre?", intent: "calendarioSemestre" },
    { question: "¿Qué fechas importantes hay en el calendario académico de este semestre?", intent: "calendarioSemestre" },
    { question: "¿Dónde encuentro el calendario académico para este semestre?", intent: "calendarioSemestre" },
    { question: "¿Calendario académico de este semestre?", intent: "calendarioSemestre" },
    { question: "¿Cuáles son las fechas del calendario académico para el semestre actual?", intent: "calendarioSemestre" },
    { question: "Cómo puedo ver el calendario académico de este semestre?", intent: "calendarioSemestre" },
    { question: "Qué fechas importantes hay en el calendario académico de este semestre?", intent: "calendarioSemestre" },
    { question: "Dónde encuentro el calendario académico para este semestre?", intent: "calendarioSemestre" },
    { question: "Calendario académico de este semestre?", intent: "calendarioSemestre" },
    { question: "Cuáles son las fechas del calendario académico para el semestre actual?", intent: "calendarioSemestre" }, 
    { question: "Cómo puedo ver el calendario académico de este semestre", intent: "calendarioSemestre" },
    { question: "Qué fechas importantes hay en el calendario académico de este semestre", intent: "calendarioSemestre" },
    { question: "Dónde encuentro el calendario académico para este semestre", intent: "calendarioSemestre" },
    { question: "Calendario académico de este semestre", intent: "calendarioSemestre" },
    { question: "Cuáles son las fechas del calendario académico para el semestre actual", intent: "calendarioSemestre" },

    // Variaciones para "¿Dónde puedo encontrar mi horario de clases?"
    { question: "¿Dónde está mi horario de clases?", intent: "horarioPersonalClase" },
    { question: "¿Cómo encuentro mi horario de clases?", intent: "horarioPersonalClase" },
    { question: "¿Dónde puedo ver el horario de clases?", intent: "horarioPersonalClase" },
    { question: "¿Dónde está disponible mi horario de clases?", intent: "horarioPersonalClase" },
    { question: "¿Cómo puedo acceder a mi horario de clases?", intent: "horarioPersonalClase" },
    { question: "Dónde está mi horario de clases?", intent: "horarioPersonalClase" },
    { question: "Cómo encuentro mi horario de clases?", intent: "horarioPersonalClase" },
    { question: "Dónde puedo ver el horario de clases?", intent: "horarioPersonalClase" },
    { question: "Dónde está disponible mi horario de clases?", intent: "horarioPersonalClase" },
    { question: "Cómo puedo acceder a mi horario de clases?", intent: "horarioPersonalClase" },
    { question: "Dónde está mi horario de clases", intent: "horarioPersonalClase" },
    { question: "Cómo encuentro mi horario de clases", intent: "horarioPersonalClase" },
    { question: "Dónde puedo ver el horario de clases", intent: "horarioPersonalClase" },
    { question: "Dónde está disponible mi horario de clases", intent: "horarioPersonalClase" },
    { question: "Cómo puedo acceder a mi horario de clases", intent: "horarioPersonalClase" },

    // Variaciones para "¿Cuándo son los períodos de inscripción para cursos?"
    { question: "¿Cuáles son las fechas de inscripción para cursos?", intent: "fechaInscripcion" },
    { question: "¿Cuándo empieza la inscripción para cursos?", intent: "fechaInscripcion" },
    { question: "¿Qué días son los períodos de inscripción para cursos?", intent: "fechaInscripcion" },
    { question: "¿Qué fechas están disponibles para inscribirse en los cursos?", intent: "fechaInscripcion" },
    { question: "¿Cuándo es el período de inscripción para los cursos?", intent: "fechaInscripcion" },
    { question: "Cuáles son las fechas de inscripción para cursos?", intent: "fechaInscripcion" },
    { question: "Cuándo empieza la inscripción para cursos?", intent: "fechaInscripcion" },
    { question: "Qué días son los períodos de inscripción para cursos?", intent: "fechaInscripcion" },
    { question: "Qué fechas están disponibles para inscribirse en los cursos?", intent: "fechaInscripcion" },
    { question: "Cuándo es el período de inscripción para los cursos?", intent: "fechaInscripcion" },
    { question: "Cuáles son las fechas de inscripción para cursos", intent: "fechaInscripcion" },
    { question: "Cuándo empieza la inscripción para cursos", intent: "fechaInscripcion" },
    { question: "Qué días son los períodos de inscripción para cursos", intent: "fechaInscripcion" },
    { question: "Qué fechas están disponibles para inscribirse en los cursos", intent: "fechaInscripcion" },
    { question: "Cuándo es el período de inscripción para los cursos", intent: "fechaInscripcion" },

    // Variaciones para "¿Dónde está la biblioteca y cuáles son sus horarios?"
    { question: "¿Dónde se encuentra la biblioteca y cuáles son sus horarios de apertura?", intent: "biblioteca" },
    { question: "¿Dónde está ubicada la biblioteca y qué horarios tiene?", intent: "biblioteca" },
    { question: "¿Dónde está la biblioteca y qué horarios tiene durante la semana?", intent: "biblioteca" },
    { question: "¿Qué horario tiene la biblioteca y dónde está?", intent: "biblioteca" },
    { question: "¿Dónde encontrar la biblioteca y sus horarios?", intent: "biblioteca" },

    // Variaciones para "¿Cómo puedo contactar al departamento de servicios estudiantiles?"
    { question: "¿Cómo contactar con el departamento de servicios estudiantiles?", intent: "contactoServiciosEstudiantiles" },
    { question: "¿Cuál es el contacto para servicios estudiantiles?", intent: "contactoServiciosEstudiantiles" },
    { question: "¿Dónde encuentro el contacto del departamento de servicios estudiantiles?", intent: "contactoServiciosEstudiantiles" },
    { question: "¿Cómo me comunico con el departamento de servicios estudiantiles?", intent: "contactoServiciosEstudiantiles" },
    { question: "¿Cuál es la forma de contacto para el departamento de servicios estudiantiles?", intent: "contactoServiciosEstudiantiles" },

    // Variaciones para "¿Hay algún evento importante en el campus esta semana?"
    { question: "¿Qué eventos importantes hay en el campus esta semana?", intent: "semanaEvento" },
    { question: "¿Hay eventos destacables en el campus esta semana?", intent: "semanaEvento" },
    { question: "¿Qué actividades importantes están planeadas para esta semana en el campus?", intent: "semanaEvento" },
    { question: "¿Eventos relevantes en el campus esta semana?", intent: "semanaEvento" },
    { question: "¿Hay algún evento significativo en el campus para esta semana?", intent: "semanaEvento" },

    // Variaciones para "¿Dónde puedo obtener ayuda si estoy experimentando estrés o problemas emocionales?"
    { question: "¿Dónde encontrar ayuda para estrés o problemas emocionales?", intent: "ayudaEmocional" },
    { question: "¿Cómo puedo obtener ayuda si tengo problemas emocionales en el campus?", intent: "ayudaEmocional" },
    { question: "¿Dónde recibir apoyo emocional si estoy estresado?", intent: "ayudaEmocional" },
    { question: "¿Dónde buscar ayuda para problemas de estrés o emocionales?", intent: "ayudaEmocional" },
    { question: "¿Qué recursos están disponibles para problemas emocionales en el campus?", intent: "ayudaEmocional" },

    // Variaciones para "¿Cuáles son los recursos disponibles para estudiantes con discapacidades?"
    { question: "¿Qué recursos hay para estudiantes con discapacidades en el campus?", intent: "recursosDiscapacidad" },
    { question: "¿Cuáles son los apoyos para estudiantes con discapacidades?", intent: "recursosDiscapacidad" },
    { question: "¿Dónde encontrar recursos para estudiantes con discapacidades?", intent: "recursosDiscapacidad" },
    { question: "¿Qué ayuda está disponible para estudiantes con discapacidades?", intent: "recursosDiscapacidad" },
    { question: "¿Cuáles son los recursos de apoyo para estudiantes con discapacidades?", intent: "recursosDiscapacidad" },

    // Variaciones para "¿Qué servicios de asesoramiento o tutoría están disponibles para mejorar mi rendimiento académico?"
    { question: "¿Qué servicios de tutoría académica están disponibles?", intent: "tutoriaAcademica" },
    { question: "¿Dónde puedo encontrar asesoramiento académico para mejorar mi rendimiento?", intent: "tutoriaAcademica" },
    { question: "¿Qué tipo de asesoramiento académico se ofrece para mejorar el rendimiento?", intent: "tutoriaAcademica" },
    { question: "¿Qué opciones de tutoría están disponibles para estudiantes?", intent: "tutoriaAcademica" },
    { question: "¿Dónde puedo recibir asesoría para mejorar mi rendimiento académico?", intent: "tutoriaAcademica" },

    // Variaciones para "¿Cómo puedo encontrar pasantías o prácticas profesionales relevantes para mi carrera?"
    { question: "¿Dónde buscar pasantías o prácticas profesionales para mi carrera?", intent: "pasantias" },
    { question: "¿Cómo encuentro pasantías relevantes para mi carrera profesional?", intent: "pasantias" },
    { question: "¿Dónde están disponibles pasantías para mi carrera?", intent: "pasantias" },
    { question: "¿Dónde encontrar prácticas profesionales relacionadas con mi carrera?", intent: "pasantias" },
    { question: "¿Cómo acceder a pasantías relevantes para mi área de estudio?", intent: "pasantias" },

    // Variaciones para "¿Qué recursos ofrece la universidad para ayudarme a escribir mi currículum vitae?"
    { question: "¿Dónde puedo obtener ayuda para escribir mi currículum vitae en la universidad?", intent: "curriculumRecursos" },
    { question: "¿Qué servicios hay para ayudarme a redactar mi currículum vitae?", intent: "curriculumRecursos" },
    { question: "¿Qué recursos ofrece la universidad para el currículum vitae?", intent: "curriculumRecursos" },
    { question: "¿Cómo puedo mejorar mi currículum vitae con los recursos de la universidad?", intent: "curriculumRecursos" },
    { question: "¿Dónde obtener ayuda para crear un currículum vitae en la universidad?", intent: "curriculumRecursos" },

    // Variaciones para "¿Hay talleres disponibles para prepararme para entrevistas de trabajo?"
    { question: "¿Dónde puedo encontrar talleres para prepararme para entrevistas?", intent: "talleresEntrevistas" },
    { question: "¿Qué talleres están disponibles para entrevistas de trabajo?", intent: "talleresEntrevistas" },
    { question: "¿Hay talleres de preparación para entrevistas de trabajo?", intent: "talleresEntrevistas" },
    { question: "¿Dónde puedo asistir a talleres para mejorar en entrevistas laborales?", intent: "talleresEntrevistas" },
    { question: "¿Qué talleres ofrece la universidad para entrevistas de trabajo?", intent: "talleresEntrevistas" },

    // Variaciones para "¿Qué clubes o actividades extracurriculares están disponibles en el campus?"
    { question: "¿Qué clubes existen en el campus?", intent: "extracurriculares" },
    { question: "¿Qué actividades extracurriculares están disponibles en el campus?", intent: "extracurriculares" },
    { question: "¿Dónde puedo encontrar clubes y actividades extracurriculares?", intent: "extracurriculares" },
    { question: "¿Cuáles son las actividades extracurriculares en el campus?", intent: "extracurriculares" },
    { question: "¿Qué clubes extracurriculares hay en el campus?", intent: "extracurriculares" },

    // Variaciones para "¿Hay alguna actividad interesante planeada para el fin de semana?"
    { question: "¿Qué actividades interesantes hay planeadas para el fin de semana?", intent: "eventoFinde" },
    { question: "¿Qué eventos importantes están previstos para el fin de semana?", intent: "eventoFinde" },
    { question: "¿Qué hay planeado para el fin de semana en el campus?", intent: "eventoFinde" },
    { question: "¿Hay alguna actividad destacable para este fin de semana?", intent: "eventoFinde" },
    { question: "¿Qué actividades interesantes están programadas para el fin de semana?", intent: "eventoFinde" },

    // Variaciones para "¿Cuáles son las opciones de alimentación disponibles en el campus?"
    { question: "¿Qué opciones de comida hay en el campus?", intent: "alimentacion" },
    { question: "¿Dónde puedo encontrar opciones de alimentación en el campus?", intent: "alimentacion" },
    { question: "¿Cuáles son los lugares para comer en el campus?", intent: "alimentacion" },
    { question: "¿Qué lugares de alimentación están disponibles en el campus?", intent: "alimentacion" },
    { question: "¿Qué opciones de alimentos hay en el campus?", intent: "alimentacion" }
];

// División en conjuntos de entrenamiento y prueba (80% entrenamiento, 20% prueba)
const trainData = dataSet.slice(0, Math.floor(dataSet.length * 0.8));
const testData = dataSet.slice(Math.floor(dataSet.length * 0.8));

// Entrenamiento con el conjunto de entrenamiento
trainData.forEach(data => {
    classifier.addDocument(data.question, data.intent);
});

classifier.train();

// Validación con el conjunto de prueba
testData.forEach(data => {
    const guess = classifier.classify(data.question);
    console.log(`Pregunta: ${data.question}, Real: ${data.intent}, Predicción: ${guess}`);
});

// Guardado del modelo
const modelPath = './model.json';
classifier.save(modelPath, err => {
    if (err) {
        console.error('Error al guardar el modelo:', err);
    } else {
        console.log('Modelo guardado con éxito en:', modelPath);
    }
});
